"""Syncing with coauthors: pull with rebase, push, and build output that always differs.

Moved here from routes/git.py so the classic /push and /pull routes and the
editor's Source control panel (routes/scm.py) share one implementation. See
docs/sync-and-conflicts.md for the design.

A real conflict (both sides changed the same lines) is handled two ways:
by default the pull is undone and Conflict is raised, which is what /push and
/pull do; with keep_conflicts=True the conflict is left in the files for the
user to resolve in the editor, and Conflict is raised with kept=True.
"""

import os
import re

from gitlatex.services import comments
from gitlatex.services.git_backend import GitCommandError

# What TeX writes next to a document. Committed copies are common (people
# commit main.pdf), and every compile rewrites them locally.
_BUILD_OUTPUT = re.compile(
    r"\.(synctex\.gz|synctex|aux|log|out|toc|lof|lot|fls|fdb_latexmk|bcf|run\.xml|blg|bbl|nav|snm|vrb|xdv)$",
    re.IGNORECASE,
)


def is_build_output(root, path):
    if _BUILD_OUTPUT.search(path):
        return True
    # A PDF is build output only when it is a document's own PDF (main.pdf next
    # to main.tex); figure PDFs are the user's files.
    if path.lower().endswith(".pdf"):
        return os.path.isfile(os.path.join(root, path[:-4] + ".tex"))
    return False


def clear_stale_build_outputs(repo):
    """Drop local build outputs that the incoming commits replace.

    Compiling rewrites main.pdf (PDFs embed a timestamp) and writes
    main.synctex.gz, so a project that commits them always looks modified, and
    `git pull` refuses to overwrite them. They are regenerated by the next
    compile anyway, so the remote's copies win. Only files the remote actually
    changes are touched; the user's own edits are left to --autostash.
    Returns the paths cleared.
    """
    try:
        if not repo.remotes or repo.head.is_detached or repo.active_branch.tracking_branch() is None:
            return []
        repo.git.fetch("--quiet")
        incoming = repo.git.diff("--name-only", "HEAD...@{u}").splitlines()
    except (GitCommandError, TypeError, ValueError):
        return []
    root = repo.working_tree_dir
    modified = set(repo.git.diff("--name-only").splitlines()) | set(repo.git.diff("--name-only", "--cached").splitlines())
    untracked = set(repo.untracked_files)
    cleared = []
    for path in incoming:
        if not is_build_output(root, path):
            continue
        try:
            if path in modified:
                repo.git.checkout("HEAD", "--", path)
                cleared.append(path)
            elif path in untracked:
                os.remove(os.path.join(root, path))
                cleared.append(path)
        except (GitCommandError, OSError) as e:
            print("Could not clear", path, e)
    return cleared


class Conflict(Exception):
    """Both sides changed the same lines. `kept`: the conflict is left in the files to resolve."""

    def __init__(self, files, kept=False):
        super().__init__(", ".join(files))
        self.files = files
        self.kept = kept


def push_current(repo):
    """Push the current branch. False if the remote has commits we don't have yet.

    GitPython reports a rejected push in the result rather than raising.
    """
    result = repo.remotes.origin.push()
    if any(info.flags & info.REJECTED for info in result):
        return False
    failed = [info for info in result if info.flags & (info.REMOTE_REJECTED | info.ERROR)]
    if failed:
        raise RuntimeError("Push failed: " + (failed[0].summary or "").strip())
    if result.error is not None and not len(result):
        raise result.error
    return True


def rebase_in_progress(repo):
    return any(os.path.isdir(os.path.join(repo.git_dir, d)) for d in ("rebase-merge", "rebase-apply"))


def unmerged(repo):
    return [f for f in repo.git.diff("--name-only", "--diff-filter=U").splitlines() if f]


def advance_rebase(repo, keep_conflicts=False):
    """Carry a stopped rebase forward past conflicts that are only build output.

    Build output keeps the local copy, since the next compile rewrites it. At a
    real conflict the rebase is aborted (Conflict), or with keep_conflicts left
    stopped for the user (Conflict with kept=True).
    """
    root = repo.working_tree_dir
    while rebase_in_progress(repo):
        files = unmerged(repo)
        real = [f for f in files if not is_build_output(root, f)]
        if keep_conflicts and real:
            # Settle the build output now, so only the user's files are left to resolve.
            build = [f for f in files if f not in real]
            if build:
                repo.git.checkout("--theirs", "--", *build)
                repo.git.add("--", *build)
            raise Conflict(real, kept=True)
        if not files or real:
            repo.git.rebase("--abort")
            raise Conflict(files)
        # During a rebase "theirs" is the local commit being replayed.
        repo.git.checkout("--theirs", "--", *files)
        repo.git.add("--", *files)
        try:
            repo.git.rebase("--continue", env={"GIT_EDITOR": "true"})
        except GitCommandError:
            pass  # the next commit stopped too; look again


def pull_rebase(repo, keep_conflicts=False):
    """`git pull --rebase --autostash`.

    Rebase rather than merge: local commits go on top of the remote's, with no
    "Merge branch" commit every time two people work at once. Comment threads
    merge through their merge driver. Conflicts only in build output (main.pdf,
    main.synctex.gz…) keep the local copy, since the next compile rewrites it
    anyway. Any other conflict undoes the whole pull, restores the user's
    uncommitted edits, and raises Conflict with the files involved — unless
    keep_conflicts, which leaves it in the files and raises Conflict(kept=True).
    """
    comments.install_merge_driver(repo.working_tree_dir)
    before = repo.head.commit.hexsha if repo.head.is_valid() else None
    try:
        output = repo.git.pull("--rebase", "--autostash")
    except GitCommandError:
        if not rebase_in_progress(repo):
            raise
    else:
        # The pull itself worked, but putting back uncommitted edits that touch
        # the same lines leaves conflict markers in the user's files (and git
        # still exits 0).
        files = unmerged(repo)
        if files and before and repo.git.stash("list", "-1", "--format=%gs") == "autostash":
            if keep_conflicts:
                raise Conflict(files, kept=True)
            # Go back to before the pull, edits and all.
            repo.git.reset("--hard", before)
            repo.git.stash("pop")
            raise Conflict(files)
        return output
    advance_rebase(repo, keep_conflicts)
    return "Pulled with rebase."
