/**
 * Live collaboration settings. Each project decides on its own whether it is
 * shared, in which room and with which room token; your colour and the owner's
 * admin login are global. Everything lives in this browser's localStorage.
 * Your name is not stored: it is your git user.name.
 */

export interface CollabConfig {
  /** Connect automatically when the project is opened. */
  enabled: boolean;
  /** The relay, e.g. `gitlatex-collab.you.workers.dev` (or `localhost:8787` when run locally). */
  host: string;
  /** Everyone who enters the same room edits together. */
  room: string;
  /** The room's own token, generated by the relay when the owner created the room. */
  token: string;
}

export interface CollabUser {
  /** Your git user.name. */
  name: string;
  color: string;
}

/** The relay owner's login, used to create rooms and their tokens. */
export interface CollabAdmin {
  host: string;
  /** The relay's ADMIN_TOKEN, chosen when it was deployed. */
  token: string;
}

/** What the owner sends to co-authors: everything needed to join one room. */
export interface CollabInvite {
  host: string;
  room: string;
  token: string;
}

/** The relay lives in its own repository, deployed to Cloudflare from the browser. */
export const RELAY_REPO = 'https://github.com/abdussamiakanda/gitlatex-collab';
export const RELAY_DEPLOY_URL = `https://deploy.workers.cloudflare.com/?url=${RELAY_REPO}`;
/** Cloudflare's "create application" page, where you connect GitHub before deploying. */
export const CLOUDFLARE_CREATE_URL = 'https://dash.cloudflare.com/?to=/:account/workers-and-pages/create';

/** A strong admin token for a new relay: 24 random bytes, base64url (32 characters). */
export function newAdminToken(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(24));
  return btoa(String.fromCharCode(...bytes)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

export const PEER_COLORS = ['#e5484d', '#f76b15', '#ffc53d', '#46a758', '#12a594', '#0090ff', '#6e56cf', '#d6409f'];

const projectKey = (projectId: string) => `gitlatex.collab.${projectId}`;
const USER_KEY = 'gitlatex.collab.user';
const ADMIN_KEY = 'gitlatex.collab.admin';
/** The last relay used, offered for the next project (its address only: tokens are per room). */
const LAST_KEY = 'gitlatex.collab.last';

/** Room names go into the URL path: keep them to a safe alphabet. */
export function roomName(input: string) {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64);
}

/** `https://x.workers.dev/` → host `x.workers.dev`, secure. Plain `localhost:8787` is not secure. */
export function splitHost(input: string): { host: string; secure: boolean } {
  const raw = input.trim();
  const m = /^(wss?|https?):\/\//i.exec(raw);
  const host = raw.replace(/^(wss?|https?):\/\//i, '').replace(/\/+$/, '');
  if (m) return { host, secure: /^(wss|https)$/i.test(m[1]) };
  return { host, secure: !/^(localhost|127\.0\.0\.1|\[::1\])(:\d+)?$/.test(host) };
}

function read<T>(key: string): Partial<T> | null {
  try {
    const raw = localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as Partial<T>) : null;
  } catch {
    return null;
  }
}

function write(key: string, value: unknown) {
  try {
    if (value === null) localStorage.removeItem(key);
    else localStorage.setItem(key, JSON.stringify(value));
  } catch {
    /* storage full / disabled */
  }
}

export function readCollabConfig(projectId: string): CollabConfig {
  const saved = read<CollabConfig>(projectKey(projectId));
  const last = read<Pick<CollabConfig, 'host'>>(LAST_KEY);
  return {
    enabled: saved?.enabled ?? false,
    host: saved?.host ?? last?.host ?? '',
    room: saved?.room ?? roomName(projectId),
    token: saved?.token ?? '',
  };
}

export function writeCollabConfig(projectId: string, config: CollabConfig) {
  write(projectKey(projectId), config);
  if (config.host) write(LAST_KEY, { host: config.host });
}

/** Carry the setting over when the project folder is renamed or deleted. */
export function moveCollabConfig(from: string, to: string | null) {
  const saved = read<CollabConfig>(projectKey(from));
  write(projectKey(from), null);
  if (saved && to) write(projectKey(to), saved);
}

/** Your cursor colour (your name comes from git). */
export function readCollabColor(): string {
  const saved = read<Pick<CollabUser, 'color'>>(USER_KEY)?.color;
  if (saved) return saved;
  const color = PEER_COLORS[Math.floor(Math.random() * PEER_COLORS.length)];
  write(USER_KEY, { color });
  return color;
}

export function writeCollabColor(color: string) {
  write(USER_KEY, { color });
}

export function readCollabAdmin(): CollabAdmin | null {
  const saved = read<CollabAdmin>(ADMIN_KEY);
  return saved?.host && saved.token ? { host: saved.host, token: saved.token } : null;
}

export function writeCollabAdmin(admin: CollabAdmin | null) {
  write(ADMIN_KEY, admin);
}

/** Same relay, however the address was typed (scheme, trailing slash, case). */
export const sameHost = (a: string, b: string) => splitHost(a).host.toLowerCase() === splitHost(b).host.toLowerCase();

// ---- invites ---------------------------------------------------------------------

const INVITE_PREFIX = 'gitlatex-invite:';

/** One string with the server, room and room token, for the owner to send. */
export function encodeInvite(invite: CollabInvite): string {
  // Keep the scheme only when it isn't the default one, so the address round-trips through splitHost.
  const { host, secure } = splitHost(invite.host);
  const json = JSON.stringify({ h: secure ? host : `http://${host}`, r: invite.room, t: invite.token });
  const b64 = btoa(String.fromCharCode(...new TextEncoder().encode(json)));
  return INVITE_PREFIX + b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/** The invite in `text`, or null when it is not one. Whitespace and line breaks are ignored. */
export function decodeInvite(text: string): CollabInvite | null {
  const raw = text.replace(/\s+/g, '');
  if (!raw.startsWith(INVITE_PREFIX)) return null;
  try {
    const b64 = raw.slice(INVITE_PREFIX.length).replace(/-/g, '+').replace(/_/g, '/');
    const bytes = Uint8Array.from(atob(b64 + '='.repeat((4 - (b64.length % 4)) % 4)), (c) => c.charCodeAt(0));
    const data = JSON.parse(new TextDecoder().decode(bytes)) as { h?: unknown; r?: unknown; t?: unknown };
    if (typeof data.h !== 'string' || typeof data.r !== 'string' || typeof data.t !== 'string') return null;
    const room = roomName(data.r);
    if (!data.h || !room || !data.t) return null;
    return { host: data.h, room, token: data.t };
  } catch {
    return null;
  }
}
